[package]
name = "scyna"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.24.0"
protobuf = "3.2.0"
protobuf-json-mapping = "3.2.0"
reqwest = { version = "0.11", features = ["blocking"] }