// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `account.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:scyna.RegisterAccountRequest)
pub struct RegisterAccountRequest {
    // message fields
    // @@protoc_insertion_point(field:scyna.RegisterAccountRequest.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:scyna.RegisterAccountRequest.email)
    pub email: ::std::string::String,
    // @@protoc_insertion_point(field:scyna.RegisterAccountRequest.password)
    pub password: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:scyna.RegisterAccountRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RegisterAccountRequest {
    fn default() -> &'a RegisterAccountRequest {
        <RegisterAccountRequest as ::protobuf::Message>::default_instance()
    }
}

impl RegisterAccountRequest {
    pub fn new() -> RegisterAccountRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &RegisterAccountRequest| { &m.name },
            |m: &mut RegisterAccountRequest| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "email",
            |m: &RegisterAccountRequest| { &m.email },
            |m: &mut RegisterAccountRequest| { &mut m.email },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "password",
            |m: &RegisterAccountRequest| { &m.password },
            |m: &mut RegisterAccountRequest| { &mut m.password },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RegisterAccountRequest>(
            "RegisterAccountRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RegisterAccountRequest {
    const NAME: &'static str = "RegisterAccountRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                18 => {
                    self.email = is.read_string()?;
                },
                26 => {
                    self.password = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if !self.email.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.email);
        }
        if !self.password.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.password);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if !self.email.is_empty() {
            os.write_string(2, &self.email)?;
        }
        if !self.password.is_empty() {
            os.write_string(3, &self.password)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RegisterAccountRequest {
        RegisterAccountRequest::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.email.clear();
        self.password.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RegisterAccountRequest {
        static instance: RegisterAccountRequest = RegisterAccountRequest {
            name: ::std::string::String::new(),
            email: ::std::string::String::new(),
            password: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RegisterAccountRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RegisterAccountRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RegisterAccountRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegisterAccountRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\raccount.proto\x12\x05scyna\"^\n\x16RegisterAccountRequest\x12\x12\n\
    \x04name\x18\x01\x20\x01(\tR\x04name\x12\x14\n\x05email\x18\x02\x20\x01(\
    \tR\x05email\x12\x1a\n\x08password\x18\x03\x20\x01(\tR\x08passwordB2\n\
    \x0eio.scyna.protoP\x01H\x02Z\x0e./;scyna_proto\xaa\x02\x0bscyna.protoJ\
    \xef\x02\n\x06\x12\x04\0\0\r\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x02\x12\x03\x02\x08\r\n\x08\n\x01\x08\x12\x03\x03\0(\n\t\n\x02\x08\
    \x01\x12\x03\x03\0(\n\x08\n\x01\x08\x12\x03\x04\0#\n\t\n\x02\x08\n\x12\
    \x03\x04\0#\n\x08\n\x01\x08\x12\x03\x05\0)\n\t\n\x02\x08%\x12\x03\x05\0)\
    \n\x08\n\x01\x08\x12\x03\x06\0!\n\t\n\x02\x08\t\x12\x03\x06\0!\n\x08\n\
    \x01\x08\x12\x03\x07\0&\n\t\n\x02\x08\x0b\x12\x03\x07\0&\n\n\n\x02\x04\0\
    \x12\x04\t\0\r\x01\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x1e\n\x0b\n\x04\x04\
    \0\x02\0\x12\x03\n\x02\x12\n\r\n\x05\x04\0\x02\0\x04\x12\x04\n\x02\t\x20\
    \n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\n\x02\x08\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\n\t\r\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\n\x10\x11\n\x0b\n\
    \x04\x04\0\x02\x01\x12\x03\x0b\x02\x13\n\r\n\x05\x04\0\x02\x01\x04\x12\
    \x04\x0b\x02\n\x12\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x0b\x02\x08\n\
    \x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x0b\t\x0e\n\x0c\n\x05\x04\0\x02\x01\
    \x03\x12\x03\x0b\x11\x12\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x0c\x02\x16\n\
    \r\n\x05\x04\0\x02\x02\x04\x12\x04\x0c\x02\x0b\x13\n\x0c\n\x05\x04\0\x02\
    \x02\x05\x12\x03\x0c\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0c\t\
    \x11\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x0c\x14\x15b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RegisterAccountRequest::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
